server:
  port: 7003
  servlet:
    context-path: /coupon-settlement

spring:
  application:
    name: eureka-client-coupon-settlement

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/
  instance:
    prefer-ip-address: true
    hostname: settlement.corn.com

logging:
  level:
    com.imooc.coupon: debug
